apiVersion: v1
kind: Secret
metadata:
  name: init-db-secrets
data:
  FLYTE_POSTGRES_PW: Zmx5dGVfcGFzc3dvcmQ= # echo -n 'flyte_password' | base64
  MLFLOW_POSTGRES_PW: bWxmbG93X3Bhc3N3b3Jk # echo -n 'mlflow_password' | base64
  KEYCLOAK_POSTGRES_PW: a2V5Y2xvYWtfcGFzc3dvcmQ= # echo -n 'keycloak_password' | base64
type: Opaque
