apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
data:
  ADMIN_PASSWORD: YWRtaW4= # echo -n 'admin' | base64
  POSTGRES_USER: a2V5Y2xvYWs= # echo -n 'keycloak' | base64
  POSTGRES_PASSWORD: a2V5Y2xvYWtfcGFzc3dvcmQ= # echo -n 'keycloak_password' | base64
type: Opaque
