apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  # persistent volumes
  - pv-minio.yaml
  - pv-postgres.yaml
  # secrets
  - minio-secret.yaml
  #- flyte-secrets.yaml
  - postgres-secret.yaml
  - s3-secret.yaml
