apiVersion: v1
kind: Secret
metadata:
  name: mlflow-storage-secret
data:
  AWS_ACCESS_KEY_ID: bWluaW8= # minio
  AWS_SECRET_ACCESS_KEY: bWluaW9fcGFzc3dvcmQ= # minio_password
  # AZURE_STORAGE_CONNECTION_STRING:
  # AZURE_STORAGE_ACCESS_KEY:
type: Opaque
