# Default values for mlflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/clemens33/mlflow
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# mlflow backend store settings
backend:
  secretName: "mlflow-backend-secret"
  # POSTGRES_USER: ... (must be provided as secret to kubernetes namespace)
  # POSTGRES_PASSWORD: ... (must be provided as secret to kubernetes namespace)
  postgres:
    host: ml-postgres
    port: 5432
    db: mlflow

# mlflow artifact store settings
storage:
  artifactsDestination: s3://mlflow/test/artifacts # s3://my-bucket-name/mlflow/artifacts
  secretName: "mlflow-storage-secret"
  # AWS_ACCESS_KEY_ID: ... (must be provided as secret to kubernetes namespace)
  # AWS_SECRET_ACCESS_KEY: ... (must be provided as secret to kubernetes namespace)
  # AZURE_STORAGE_CONNECTION_STRING: ... (must be provided as secret to kubernetes namespace)
  # AZURE_STORAGE_ACCESS_KEY: ... (must be provided as secret to kubernetes namespace)
  s3:
    endpointUrl: http://ml-minio:9000
    ignoreTls: true
    defaultRegion: us-east-1
  azure:
    uploadDownloadTimeout: 1200

# mlflow settings
exposePrometheusMetrics: true
workers: 2

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: localhost
      paths:
        - path: /mlflow(/|$)(.*)
          pathType: ImplementationSpecific
  tls: []

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
