apiVersion: v1
kind: PersistentVolume
metadata:
  name: rwo-pv-minio
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv/rwo/minio
  storageClassName: host-path-minio
