apiVersion: v1
kind: PersistentVolume
metadata:
  name: rwo-pv-postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv/rwo/postgres
  storageClassName: host-path-postgres
