kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ml-stack
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 8888
        protocol: TCP
      - containerPort: 443
        hostPort: 44388
        protocol: TCP
  - role: worker
    labels:
      worker: "1"
    extraMounts:
      - hostPath: data
        containerPath: /data
