apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization

resources:
  - localdev

helmCharts:
  - name: postgresql
    releaseName: ml-postgres
    includeCRDs: true
    repo: https://charts.bitnami.com/bitnami
    version: ~13.1.5
    #version: "*"
    valuesFile: localdev/postgres-values.yaml
    valuesInline:
      fullnameOverride: "ml-postgres"
      image:
        tag: 16.1.0-debian-11-r15
        # tag: latest

  - name: minio
    releaseName: ml-minio
    includeCRDs: true
    repo: https://charts.bitnami.com/bitnami
    version: ~12.8.15
    # version: "*"
    valuesFile: localdev/minio-values.yaml
    valuesInline:
      fullnameOverride: "ml-minio"
      image:
        tag: 2023.12.7-debian-11-r0
        # tag: latest

  - name: mlflow
    releaseName: mlflow
    includeCRDs: true
    repo: https://clemens33.github.io/mlflow/
    version: 2.9.2-2
    # version: "*"
    valuesFile: localdev/mlflow-values.yaml
    valuesInline:
      fullnameOverride: "ml-mlflow"
      image:
        repository: docker.io/clemens33/mlflow
        tag: 2.9.2-py3.11
        # tag: latest

  - name: flyte-binary
    releaseName: flyte
    includeCRDs: true
    repo: https://helm.flyte.org/
    version: v1.10.6
    #version: "*"
    valuesFile: localdev/flyte-binary-values.yaml
    valuesInline:
      fullnameOverride: "ml-flyte"
      image:
        repository: cr.flyte.org/flyteorg/flyte-binary-release
        tag: v1.10.6

  - name: keycloak
    releaseName: keycloak
    includeCRDs: true
    repo: https://charts.bitnami.com/bitnami
    version: "17.3.6"
    #version: "*"
    valuesFile: localdev/keycloak-values.yaml
    valuesInline:
      fullnameOverride: "ml-keycloak"
      image:
        tag: 22.0.5-debian-11-r4

generatorOptions:
  disableNameSuffixHash: true
